### ISSUE TITLE
Looking to help

### ISSUE THREAD

**Issue by billdueber** [cbeer/solr_wrapper#1]
I have no idea what you're doing here, and yet instantly want to help. :-)

I did some of this sort of admin work with [SimpleSolrClient](https://github.com/billdueber/simple_solr), but already your stuff looks betterererer. Lemme know if you want an extra set of eyes.

**Comment by cbeer** [comment]
I'm just replacing github.com/projecthydra/jettywrapper with something for Solr 5 (and, in fact, have pulled in SimpleSolrClient for integration testing.)
