### ISSUE TITLE
Stash the downloads?

### ISSUE THREAD

**Issue by darrenleeweber** [cbeer/solr_wrapper#103]
Stash the downloads into a tmp folder for safe keeping, check the tmp folder for the downloads before downloading them again?  (Perhaps just download the md5 and use it to verify the stash again if a double check is required.)  This could save some time when using solr_wrapper during transit-time development activities (commuting or flights or just anywhere with lousy network connections). e.g.

```
./tmp/solr_wrapper/solr-6.5.1.zip
./tmp/solr_wrapper/solr-6.5.1.zip.md5
```

**Comment by cbeer** [comment]
They are stashed in the system tmp dir. You can change the stash location either on a project-by-project (using a `.solr_wrapper.yml` file) or global basis (using `~/.solr_wrapper.yml`) by setting e.g.:

```yaml
download_dir: /Users/cabeer/tmp
```
