### ISSUE TITLE
Idea: Version as X.Y.Z.A, where X.Y.Z is the solr version targeted

### ISSUE THREAD

**Issue by billdueber** [cbeer/solr_wrapper#107]
I don't know if this is a good idea or not, but it sure would make it easy to know which version of the wrapper will be downloading which version of solr.

Just a thought from an impressed user.

**Comment by jcoyne** [comment]
@billdueber Typically solr_wrapper checks the Solr website for the latest version if you haven't specified a version in the config file.  Only if that fails does it fall back to a default version.  This means there's typically no need to track upstream versions.
