### ISSUE TITLE
release 1.3.0 with mirror_url?

### ISSUE THREAD

**Issue by jrochkind** [cbeer/solr_wrapper#116]
Last week, a number of people are having trouble with tests on travis, timing out at the point solr_wrapper is trying to download solr.  An example stack trace on travis: https://travis-ci.org/sciencehistory/chf-sufia/builds/377350433

Several [reported](https://github.com/psu-libraries/cho/commit/7f85079d91c1cdb32dee5bd21df0ba1fa380b8d5) that using solr_wrapper from git, with the [mirror_url feature](https://github.com/cbeer/solr_wrapper/pull/113/files), and pointing mirror_url in config to princeton's mirror at `http://lib-solr-mirror.princeton.edu/dist/` resolved the issue and let travis pass again.  It was reported by several to be a fix. (I didn't try it myself while the problem was still going on). 

This week, it no longer seems to be a problem. That does kind of suggest it's the issue with apache.org rate-limiting travis IPs, which seems to crop up now and then. So it will probably be an issue again. 

As far as I can tell, the mirror_url feature is not in a released gem. Would it be possible to get a 1.3.0 of solr_wrapper released including the mirror_url, so we can use it, and avoid the apparent apache.org rate-limiting problem in the future?

I really prefer using actual releases on rubygems instead of dependencies to a git commit from github. Our dependency tree is confusing enough already.  I know I'm not alone here.  Would really appreciate a release. 

Thank you!

**Comment by dkinzer** [comment]
I would like to add that the mirror_url feature does not currently work as advertised and that #114 is meant to fix that.  Hopefully that will be merged before this next release is out.

**Comment by jrochkind** [comment]
oh, I didn't realize that, thanks @dkinzer . Yes, then both I guess. 

When travis stops being able to get solr for running tests, which has happened to me multiple times now, it really is a big problem.
