### ISSUE TITLE
Export rake tasks to downstream users

### ISSUE THREAD

**Issue by mjgiarlo** [cbeer/solr_wrapper#22]
So that we can, e.g., rake solr:start.

We did this in jettywrapper: https://github.com/projecthydra/jettywrapper/blob/master/Rakefile#L7

**Comment by cbeer** [comment]
Aren't they? https://github.com/cbeer/solr_wrapper#rake-tasks

**Comment by mjgiarlo** [comment]
Ah, yes. Closing!
