### ISSUE TITLE
Duplicate options

### ISSUE THREAD

**Issue by val99erie** [cbeer/solr_wrapper#27]
In the OptionParser it looks like you are using the -d option twice.

Here:
https://github.com/cbeer/solr_wrapper/blob/master/exe/solr_wrapper#L35

and here:
https://github.com/cbeer/solr_wrapper/blob/master/exe/solr_wrapper#L51

**Comment by cbeer** [comment]
Thanks, fixed in e8090b8 (and released as v0.6.1)
