### ISSUE TITLE
poll push

### ISSUE THREAD

**Issue by rkhet** [cbeer/solr_wrapper#29]
When I run the solr server via solr_wrapper it writes to solr.log and solr-port-concole.log every second..

`2016-03-09 23:15:27.822 INFO  (qtp1450821318-18) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json} status=0 QTime=4`

Is this by design.  It seems to chew quite a bit of cycles w/out any requests.

**Comment by cbeer** [comment]
Finally fixed by #46. Instead of using the solr-provided status check, we first check if the PID is still running, at the risk of false positives.
