### ISSUE TITLE
Downloading Solr fails after new version is released

### ISSUE THREAD

**Issue by escowles** [cbeer/solr_wrapper#62]
After a new version of Solr is released, the old version is quickly removed from the Apache mirrors, so downloading fails.

Can we fallback on using the Apache archive for older releases, and log a prominent warning message to let people know they should update?

**Comment by jcoyne** [comment]
Wasn't this fixed in https://github.com/cbeer/solr_wrapper/pull/57?

**Comment by escowles** [comment]
@jcoyne Look like it was. I just saw this problem again with 0.12 — sorry for not checking the current release before complaining!
