### ISSUE TITLE
Orphaned java process after starting with Foreman

### ISSUE THREAD

**Issue by electrickite** [cbeer/solr_wrapper#70]
When starting solr_wrapper using [Foreman](https://github.com/ddollar/foreman), sending an interrupt (Ctl+C) to Foreman leaves an orphaned java process still running Solr. The solr_wrapper binary exits, but it leaves the java process running. Observed on OS X 10.11.5.

To reproduce:

1. Add `solr_wrapper` and `foreman` to the `Gemfile`
2. `bundle install`
3. Create a `Procfile` containing `solr: solr_wrapper -p 8983`
4. Run `bundle exec foreman start`
5. Allow Solr to start up
6. Press Ctl+C to kill Foreman
7. Run `ps aux | grep "[j]ava"` and observe Solr still running.

The issue does not seem to happen on every run, but happens with some regularity.

A repo demonstrating the issue can be found here: https://github.com/electrickite/solr_wrapper_foreman

**Comment by jcoyne** [comment]
`solr_wrapper` does basically the same job as foreman, so I wonder why you bother wrapping `solr_wrapper` and not just `$ bin/solr start`?

**Comment by electrickite** [comment]
@jcoyne I certainly could, although that requires knowledge of where solr_wrapper stores the solr binary and the arguments the user initially used to trigger the Solr download. The solr_wrapper command encapsulates all of this logic and allows for a generic Procfile to be written.
