### ISSUE TITLE
Explicit config silently ignored

### ISSUE THREAD

**Issue by atz** [cbeer/solr_wrapper#72]
From `.internal_test_app` I run:
```
solr_wrapper -v -d solr/config/ -n hydra-test -p 8985
```
I expect the running solr to use the configurations supplied at `solr/config`.  

But the live solrconfig at [http://127.0.0.1:8985/solr/#/hydra-test/files?file=solrconfig.xml](http://127.0.0.1:8985/solr/#/hydra-test/files?file=solrconfig.xml) doesn't match `solr/conf/solrconfig.xml`, i.e. the configuration I specified directly.

Maybe this is from invoking solr_wrapper previously?  If so, the mode of silently ignoring the command is bogus.  I would expect to use serial execution to facilitate testing different configurations, like:
```
solr_wrapper -v -d solr/config/ -n hydra-test -p 8985
solr_wrapper -v -d solr/config2/ -n hydra-test -p 8985
solr_wrapper -v -d solr/config3/ -n hydra-test -p 8985
```
If it cannot, then I expect it to complain loudly, at a minimum.  Preferably it should **fail** loudly, since it cannot do the one thing `solr_wrapper` is good for.

**Comment by atz** [comment]
Looks like part of my problem is Sufia's `engine_cart:generate` creating both:
- `.internal_test_app/solr/conf` and
- `.internal_test_app/solr/config`

That is confusing.

**Comment by cbeer** [comment]
I'm unable to recreate this, either in isolation or with a `.solr_wrapper.yml` file pointing at a different config. Hopefully you'll file the Sufia issue with them?

**Comment by atz** [comment]
Yeah, I think this is just Sufia's problem, not engine_cart.  Sorry for the crossed wires.
