### ISSUE TITLE
hydra 10 depending on solr_wrapper 0.12.1 which appears to have a non existant mirror reference

### ISSUE THREAD

**Issue by rkhet** [cbeer/solr_wrapper#73]
When I pull hydra 10.0.0 I get in hydra.gemspec..
_gem.add_dependency 'solr_wrapper', '~> 0.12.1'_

which I mention because of..
https://github.com/projecthydra/hydra/pull/108

and with that setup my initial run of solr_wrapper attmpts to download..
http://www.trieuvan.com/apache/lucene/solr/6.0.1/solr-6.0.1.zip

which does not exist there.

Is _solr_wrapper 0.12.1_ the proper version for hydra 10?
Where is the download url set and is the version of solr correct.  I do find..
_...solr/6.1.0/solr-6.1.0.zip_ at the trieuvan site above.  I can't seem to find where, in the _solr_wrapper-0.12.1_ source where config.download_url is set.

**Comment by cbeer** [comment]
Apache's mirroring policy is to remove all older versions from its mirrors. `solr_wrapper` 0.13 added additional logic to fall back to their archive host. It seems like the hydra gemspec is too restrictive and should be loosen there.

In the meantime, you should be able to create a `.solr_wrapper` file in the root of your project that points to archive mirror, e.g.:

```
url: http://archive.apache.org/dist/lucene/solr/6.0.1/solr-6.0.1.zip
```

**Comment by jcoyne** [comment]
I think the hydra gemspec was intended to be restrictive. The problem is that it only gets attention once or twice a year (before conference workshops). @rkhet you could submit a pr on the hydra gem to bump the version.

**Comment by rkhet** [comment]
Thanks gents.  I'll get a pull request in soon.  For my edification, were do the mirror urls come from?  Are they pulled from a service themselves?

**Comment by rkhet** [comment]
And one other question.  I altered the version of the solr_wrapper dependency in hydra.gemspec to 0.13.1 but my Gemfile.lock was still generated w/ _solr_wrapper (~> 0.12.1)_  What's forcing the solr_wrapper version?

**Comment by rkhet** [comment]
Let's see I'm a bit new digging in here.  A 'url' key/value added to .solr_wrapper in my project has no affect.

**Comment by jcoyne** [comment]
@rkhet `bundle update` with update the `Gemfile.lock`

**Comment by rkhet** [comment]
Thanks.  I eventually pulled from the url @cbeer got me..was running the wrapper from the wrong place.  However now the md5 validation is failing.  Not sure where that's pulled from for a given solr zip.  I'm going to alter solr_wrapper code for now to get it up and running.

**Comment by cbeer** [comment]
You should also be able to use `--ignore_md5sum` or add `ignore_md5sum: true` to that file.

**Comment by rkhet** [comment]
One odd thing I thought, the "hydra-development" core gets created per the "name" key in .solr_wrapper however the next time I try restart I get an error stating the core already exists and need to comment the "name:" line out of .solr_wrapper to allow it to not try another create.  Thx for the assist
